### ISSUE TITLE
Raster time check on mr.makeDelay would help

### ISSUE THREAD

**Issue by sairamgeethanath** [pulseq/pulseq#4]
A check on whether the prescribed delay in the delay block is a positive integer multiple of gradient  rastertime would help in catching errors where delay might be computed elsewhere or in other parts of the code. Alternately ceiling/rounding with the developer's knowledge may also be considered.

**Comment by stefan-k** [comment]
Thanks. We have also noticed this problem. Unfortunately the system limits need to be propagated in order to do this. Many functions already allow the limits to be passed in, but this is not very ergonomic. We are thinking about a different design where all event-creating functions are methods of the Sequence class. That way all system limitations are readily available.

**Comment by m-a-x-i-m-z** [comment]
seq.checkTiming() does this kind of checks in the current public version
